"""Build the night sky's data for the game.

Two outputs, both regenerated by running this script, never edited:

- game/data/stars.bin: every star of the Yale Bright Star Catalogue
  (5th edition, Hoffleit and Warren 1991, public domain; the copy in
  tools/data/bsc5-short.json is from
  github.com/brettonw/YaleBrightStarCatalog). Four little-endian float32
  per star: right ascension and declination (J2000, radians), visual
  magnitude, and temperature in kelvin.

- game/world/milky_way.png: the Milky Way's light in galactic
  coordinates, longitude 180 to -180 across (increasing to the left,
  as on the sky) and latitude +40 to -40 down, the square root of the
  surface brightness in each channel. A model of the Galaxy as the eye
  sees it from a dark site: a disc of light thickest and brightest
  toward the centre in Sagittarius, a second swell in Cygnus, the star
  clouds of Sagittarius, Scutum and Cygnus, mottled on every scale, cut
  along its middle by dust: the Great Rift from Cygnus to Sagittarius,
  the Aquila Rift, the dark streamers of Ophiuchus, the Taurus clouds;
  faint toward the anticentre in Auriga. Warmer toward the centre.

Pure Python: run it with the project's interpreter; it takes a minute
or two.
"""

from __future__ import annotations

import json
import math
import random
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "tools" / "data" / "bsc5-short.json"
STARS_OUT = ROOT / "game" / "data" / "stars.bin"
MILKY_OUT = ROOT / "game" / "world" / "milky_way.png"

W = 2048
H = 456            # 80 degrees of latitude at the same scale as longitude
B_SPAN = 40.0


# ---- the catalogue ---------------------------------------------------------

def _ra(text: str) -> float:
    h, m, s = text.replace("h", " ").replace("m", " ").replace("s", " ").split()
    return math.radians((float(h) + float(m) / 60.0 + float(s) / 3600.0) * 15.0)


def _dec(text: str) -> float:
    sign = -1.0 if text.strip().startswith("-") else 1.0
    parts = text.strip().lstrip("+-").replace("°", " ").replace("′", " ").replace("″", " ").split()
    d, m, s = (float(p) for p in parts)
    return sign * math.radians(d + m / 60.0 + s / 3600.0)


def build_stars() -> int:
    rows = json.loads(CATALOGUE.read_text(encoding="utf-8"))
    out = bytearray()
    count = 0
    for row in rows:
        try:
            v = float(row["V"])
        except (KeyError, ValueError):
            continue
        kelvin = float(row.get("K") or 5800.0)
        out += struct.pack("<4f", _ra(row["RA"]), _dec(row["Dec"]), v, kelvin)
        count += 1
    STARS_OUT.write_bytes(bytes(out))
    return count


# ---- the Milky Way ---------------------------------------------------------

class Noise:
    """Value noise on a lattice wrapping in longitude, smooth-stepped."""

    def __init__(self, seed: int, cells_l: int, cells_b: int) -> None:
        rng = random.Random(seed)
        self.nl = cells_l
        self.nb = cells_b
        self.v = [[rng.random() for _ in range(cells_b + 2)] for _ in range(cells_l)]

    def at(self, u: float, v: float) -> float:
        # u in [0, 1) round the sky, v in [0, 1] across the band.
        x = u * self.nl
        y = v * self.nb
        i = int(math.floor(x))
        j = int(math.floor(y))
        fx = x - i
        fy = y - j
        fx = fx * fx * (3.0 - 2.0 * fx)
        fy = fy * fy * (3.0 - 2.0 * fy)
        i0 = i % self.nl
        i1 = (i + 1) % self.nl
        j0 = min(max(j, 0), self.nb + 1)
        j1 = min(j0 + 1, self.nb + 1)
        a = self.v[i0][j0] + (self.v[i1][j0] - self.v[i0][j0]) * fx
        b = self.v[i0][j1] + (self.v[i1][j1] - self.v[i0][j1]) * fx
        return a + (b - a) * fy


def _fbm(octaves: list[Noise], u: float, v: float) -> float:
    total = 0.0
    amp = 0.5
    norm = 0.0
    for n in octaves:
        total += amp * n.at(u, v)
        norm += amp
        amp *= 0.55
    return total / norm


def _gauss(x: float, s: float) -> float:
    return math.exp(-(x / s) ** 2)


def _dl(l: float, l0: float) -> float:
    """Longitude difference wrapped to [-180, 180)."""
    return (l - l0 + 180.0) % 360.0 - 180.0


def brightness(l: float, b: float, mottle: float, fine: float, dust_n: float, streak: float) -> tuple[float, float]:
    """Surface brightness at galactic (l, b) in degrees, and warmth 0..1."""
    lc = _dl(l, 0.0)
    # Along the plane: the centre, the Cygnus swell, falling to the anticentre.
    along = (0.34 + 0.66 * _gauss(lc, 45.0) + 0.45 * _gauss(_dl(l, 78.0), 24.0)
             + 0.22 * _gauss(_dl(l, 125.0), 25.0) + 0.25 * _gauss(_dl(l, -60.0), 25.0))
    # Across it: thicker toward the centre, the bulge rounder still.
    h = 4.2 + 3.8 * _gauss(lc, 28.0)
    disc = math.exp(-abs(b) / h) * 0.6 + 0.4 * _gauss(b, h * 0.8)
    bulge = 0.55 * math.exp(-math.sqrt(lc * lc + (b * 1.4) ** 2) / 9.0)
    wide = 0.05 * math.exp(-abs(b) / 22.0)
    light = along * disc + bulge + wide
    # The star clouds.
    light += 0.6 * _gauss(math.hypot(_dl(l, 2.0), b + 4.0), 4.0)       # Sagittarius
    light += 0.55 * _gauss(math.hypot(_dl(l, 27.5), b + 2.5), 2.6)     # Scutum
    light += 0.45 * _gauss(math.hypot(_dl(l, 76.0), b - 1.0), 5.0)     # Cygnus
    light += 0.25 * _gauss(math.hypot(_dl(l, 12.0), b + 1.0), 3.0)     # small Sagittarius cloud
    # Mottled on every scale.
    light *= 0.45 + 1.1 * mottle
    light *= 0.75 + 0.5 * fine
    # Dust along the middle, strongest inward.
    tau = 0.0
    mid = 0.9 * _gauss(b - 0.4, 1.6 + 1.2 * _gauss(lc, 30.0)) * (0.35 + 0.65 * _gauss(lc, 70.0))
    tau += mid * (0.5 + dust_n)
    # The Great Rift: from Cygnus down to Sagittarius, north of the middle
    # line, widening through Aquila.
    if -15.0 < lc < 90.0:
        centre_b = 1.8 + 2.5 * _gauss(lc - 30.0, 18.0) + 0.8 * math.sin(math.radians(lc * 6.0))
        width = 2.2 + 3.0 * _gauss(lc - 30.0, 15.0)
        rift = _gauss(b - centre_b, width) * min(1.0, (lc + 15.0) / 12.0) * min(1.0, (90.0 - lc) / 15.0)
        tau += 1.8 * rift * (0.4 + 0.9 * streak)
    # Ophiuchus: dark streamers reaching north from the centre.
    if -10.0 < lc < 25.0 and 2.0 < b < 22.0:
        tau += 1.2 * _gauss(lc - 5.0 + (b - 5.0) * 0.5, 4.0) * _gauss(b - 9.0, 7.0) * (0.3 + streak)
    # Taurus and Perseus clouds, faint, south of the anticentre.
    tau += 0.6 * _gauss(math.hypot(_dl(l, 172.0), b + 15.0), 6.0) * (0.4 + dust_n)
    light *= math.exp(-tau)
    warmth = _gauss(lc, 50.0)
    return light, warmth


def build_milky_way() -> None:
    mottle_o = [Noise(11 + k, 48 * 2 ** k, int(12 * 2 ** k)) for k in range(4)]
    fine_o = [Noise(51 + k, 360 * 2 ** k, int(80 * 2 ** k)) for k in range(2)]
    dust_o = [Noise(91 + k, 180 * 2 ** k, int(40 * 2 ** k)) for k in range(3)]
    streak_o = [Noise(131 + k, 60 * 2 ** k, int(90 * 2 ** k)) for k in range(3)]
    rows = []
    peak = 0.0
    values: list[list[tuple[float, float]]] = []
    for y in range(H):
        b = B_SPAN - 2.0 * B_SPAN * (y + 0.5) / H
        v = (y + 0.5) / H
        row: list[tuple[float, float]] = []
        for x in range(W):
            l = 180.0 - 360.0 * (x + 0.5) / W
            u = ((l % 360.0) / 360.0)
            m = _fbm(mottle_o, u, v)
            f = _fbm(fine_o, u, v)
            d = _fbm(dust_o, u, v)
            s = _fbm(streak_o, u, v)
            light, warm = brightness(l, b, m, f, d, s)
            peak = max(peak, light)
            row.append((light, warm))
        values.append(row)
    for row in values:
        out = bytearray([0])
        for light, warm in row:
            n = math.sqrt(max(light, 0.0) / peak)
            r = n * (0.94 + 0.08 * warm)
            g = n * (0.95 + 0.02 * warm)
            bl = n * (1.0 - 0.10 * warm)
            out += bytes(int(max(0.0, min(1.0, c)) * 255.0 + 0.5) for c in (r, g, bl))
        rows.append(bytes(out))
    _write_png(MILKY_OUT, W, H, b"".join(rows))


def _write_png(path: Path, w: int, h: int, raw: bytes) -> None:
    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)
    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9))
    png += chunk(b"IEND", b"")
    path.write_bytes(png)


if __name__ == "__main__":
    n = build_stars()
    print(f"stars.bin: {n} stars")
    build_milky_way()
    print(f"milky_way.png: {W} x {H}")
